package com.wasteflow.ecocycle.ui.theme

import androidx.compose.ui.graphics.Color

val EcoPrimary = Color(0xFF3E6A00)
val EcoPrimaryContainer = Color(0xFF8BC34A)
val EcoOnPrimaryContainer = Color(0xFF2D4E00)
val EcoPrimaryFixed = Color(0xFFB9F474)
val EcoPrimaryFixedDim = Color(0xFF9ED75B)
val EcoSurface = Color(0xFFF8FBEC)
val EcoSurfaceContainer = Color(0xFFEDEFE1)
val EcoSurfaceContainerHigh = Color(0xFFE7EADC)
val EcoSurfaceContainerHighest = Color(0xFFE1E4D6)
val EcoSurfaceContainerLow = Color(0xFFF2F5E7)
val EcoSurfaceContainerLowest = Color(0xFFFFFFFF)
val EcoOnSurface = Color(0xFF191D14)
val EcoOnSurfaceVariant = Color(0xFF424939)
val EcoInverseSurface = Color(0xFF2E3228)
val EcoInverseOnSurface = Color(0xFFEFF2E4)
val EcoError = Color(0xFFBA1A1A)
val EcoErrorContainer = Color(0xFFFFDAD6)
val EcoOnErrorContainer = Color(0xFF93000A)
val EcoTertiary = Color(0xFF5D5F5F)
val EcoTertiaryContainer = Color(0xFFB2B3B3)
val EcoSecondaryContainer = Color(0xFFE2E2E2)
val EcoOutline = Color(0xFF737A67)
val EcoOutlineVariant = Color(0xFFC2C9B4)
val EcoBlack = Color(0xFF191D14)
val EcoWhite = Color(0xFFFFFFFF)
